# Generated by Django 4.2.23 on 2026-04-24 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campeonato", "0002_alter_campus_options_alter_modalidade_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[],
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("campeonato.modalidade",),
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("campeonato.jogador",),
        ),
    ]
